name: MysticMinigames
author: QuickScythe
version: 3.5.1
description: Runs the MysticCloud minigame server
api-version: 1.20
api: Spigot
main: net.mysticcloud.spigot.minigames.MysticMinigames
commands: